# Generated by Django 5.2 on 2025-04-28 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('limite_co', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limite_nox', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usa_obd', models.BooleanField()),
                ('frecuencia_meses', models.PositiveIntegerField()),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('tipo_combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('usa_obd', models.BooleanField()),
                ('co_medido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nox_medido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('co_emitido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nox_emitido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obd_funciona', models.BooleanField()),
                ('aprobada', models.BooleanField()),
                ('normativa_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_regulaciones.normativa')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_regulaciones.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('motivo', models.TextField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_regulaciones.vehiculo')),
                ('verificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_regulaciones.verificacion')),
            ],
        ),
    ]
