# Generated by Django 5.2 on 2025-05-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regulacion',
            fields=[
                ('id_regulacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=100)),
                ('limite_HO', models.IntegerField()),
                ('limite_CO', models.IntegerField()),
                ('limite_NO', models.IntegerField()),
                ('limite_O2', models.IntegerField()),
                ('dilucion', models.IntegerField()),
                ('factor_lambda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio_verificacion', models.DateField()),
                ('fecha_fin_verificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Trabajador', 'Trabajador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('propietario', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('combustible', models.CharField(max_length=50)),
                ('cilindros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=20)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('HO', models.IntegerField()),
                ('CO', models.IntegerField()),
                ('NO', models.IntegerField()),
                ('O2', models.IntegerField()),
                ('dilucion', models.IntegerField()),
                ('factor_lambda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resultado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('id_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Técnico', 'Técnico'), ('Revisor', 'Revisor')], max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_imposicion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo'),
        ),
    ]
