# Generated by Django 5.2 on 2025-05-06 04:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_combustible', models.CharField(max_length=20)),
                ('limite_co', models.DecimalField(decimal_places=2, max_digits=6)),
                ('limite_nox', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usa_obd', models.BooleanField()),
                ('frecuencia_meses', models.IntegerField()),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('tipo_combustible', models.CharField(max_length=20)),
                ('usa_obd', models.BooleanField()),
                ('co_medido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nox_medido', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada')], max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo', to_field='placa')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('estado', models.BooleanField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=10)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('co_emitido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nox_emitido', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obd_funciona', models.BooleanField()),
                ('aprobada', models.BooleanField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cita')),
                ('normativa_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.normativa')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.vehiculo', to_field='placa')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('id_verificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.verificacion')),
            ],
        ),
    ]
