# Generated by Django 5.2 on 2025-05-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacion',
            name='id_cita',
        ),
    ]
